health: # Healing configuration, all values in %
  healingPotionAt: 80
  manaPotionAt: 60
  rejuvPotionAtLife: 40
  rejuvPotionAtMana: 40
  mercHealingPotionAt: 60
  mercRejuvPotionAt: 20

bindings:
  potionHP: 1
  potionMANA: 4
  potionREJUV: 2